/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
        },
        bg: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        'surface-solid': 'var(--color-surface-solid)',
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
          'on-primary': 'var(--color-text-on-primary)',
        },
        border: 'var(--color-border)',
        'border-focus': 'var(--color-border-focus)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        error: 'var(--color-error)',
        info: 'var(--color-info)',
        type: {
          class: 'var(--color-type-class)',
          personal: 'var(--color-type-personal)',
          rest: 'var(--color-type-rest)',
          other: 'var(--color-type-other)',
        },
        mood: {
          1: 'var(--color-mood-1)',
          2: 'var(--color-mood-2)',
          3: 'var(--color-mood-3)',
          4: 'var(--color-mood-4)',
          5: 'var(--color-mood-5)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
      },
      fontSize: {
        xs: ['var(--text-xs-size)', 'var(--text-xs-height)'],
        sm: ['var(--text-sm-size)', 'var(--text-sm-height)'],
        base: ['var(--text-base-size)', 'var(--text-base-height)'],
        lg: ['var(--text-lg-size)', 'var(--text-lg-height)'],
        xl: ['var(--text-xl-size)', 'var(--text-xl-height)'],
        '2xl': ['var(--text-2xl-size)', 'var(--text-2xl-height)'],
        '3xl': ['var(--text-3xl-size)', 'var(--text-3xl-height)'],
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        glow: 'var(--shadow-glow)',
      },
      backdropBlur: {
        sm: 'var(--blur-sm)',
        md: 'var(--blur-md)',
        lg: 'var(--blur-lg)',
      },
    },
  },
  plugins: [],
}
